### ISSUE TITLE
Invalid discord link

### ISSUE THREAD

**Issue by kaleem68** [Semalab/template#2]
In
[CONTRIBUTING.md](https://github.com/Semalab/template/blob/main/CONTRIBUTING.md)

It mentions an invalid discord link

[Join our Discord community](https://discord.gg/cEQHZz34)

Please fix it.

**Comment by kaleem68** [comment]
Following repos have invalid discord links.

https://github.com/Semalab/template/blob/main/CONTRIBUTING.md
https://github.com/Semalab/oswc-query-bot/blob/main/CONTRIBUTING.md
https://github.com/Semalab/developer-rubric-slack-bot/blob/main/CONTRIBUTING.md
https://github.com/Semalab/developer-rubric/blob/main/CONTRIBUTING.md
https://github.com/Semalab/developer-rubric-discord-bot/blob/main/CONTRIBUTING.md

**Comment by PrajwalBorkar** [comment]
Fixed the links 👍

**Comment by kaleem68** [comment]
@PrajwalBorkar Where has it been fixed? I still see an invalid link in https://github.com/Semalab/template/blob/main/CONTRIBUTING.md

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar Where has it been fixed? I still see an invalid link in https://github.com/Semalab/template/blob/main/CONTRIBUTING.md

Here already a PR is open related to this issue.

**Comment by naomi-lgbt** [comment]
Thanks to @PrajwalBorkar for updating the links on these repos! This issue should now be resolved.
